# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
dist: trusty
warnings_are_errors: false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - cd comcat

jobs:
  include:
#  - r: devel
  - r: release

r_packages:
 - httr
 - purrr
 - readr
 - jsonlite
 - XML2R
 - rgdal
 - testthat
 - covr
# - knitr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
